title: WoT это Классика
description: >-
  Серия модификаций "WoT это Классика!" возвращает атмосферу "те самые танки"
  через интерфейсные, графические и звуковые моды. Они придают игре ностальгическое ощущение,
  перенося вас во времена классической игры и воссоздавая те эмоции, что так привлекали игроков.
baseurl: ""
url: "https://wot-classic.ru"

plugins:
  - jekyll-paginate-v2

pagination:
  enabled: true
  per_page: 10
  permalink: '/news/:num/'
  sort_reverse: true
  title: ':title'
  trail:
    before: 1
    after: 1

autopages:
  enabled: true
  categories:
    layouts:
      - 'paginator.html'
    permalink: '/news/:cat/'
    title: Категории
  tags:
    enabled: false
  collections:
    enabled: false

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

collections:
  dev-posts:
    output: true
  archive:
    output: true
  guide:
    output: true
  fan-pages:
    output: true

defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      permalink: "/news/:title/"
  - scope:
      path: ""
      type: "dev-posts"
    values:
      layout: "dev-post"
      permalink: "/development/:title/"
  - scope:
      path: ""
      type: "guide"
    values:
      layout: "guidee"
      permalink: "/guide/:title/"
  - scope:
      path: ""
      type: "archive"
    values:
      layout: "archive-post"
      permalink: "/updates/:categories/:title/"
  - scope:
      path: ""
      type: "fan-pages"
    values:
      layout: "fan-page"
      permalink: "/fan-pages/:name/"
  - scope:
      path: ""
    values:
      layout: "default"

kramdown:
  transliterated_header_ids: true
