title: WoT это Классика
description: >-
  Серия модификаций "WoT это Классика!" возвращает атмосферу "те самые танки"
  через интерфейсные, графические и звуковые моды. Они придают игре ностальгическое ощущение,
  перенося вас во времена классической игры и воссоздавая те эмоции, что так привлекали игроков.
baseurl: ""
url: "https://wotclassic.github.io"

plugins:
  - jekyll-paginate-v2

pagination:
  enabled: true
  per_page: 10
  permalink: '/news/:num/'
  sort_reverse: true
  title: ':title'
  trail:
    before: 1
    after: 1

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      permalink: "/news/:title/"
  - scope:
      path: ""
    values:
      layout: "default"
