title: WoT это Классика
description: >- # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "/wotclassic" # the subpath of your site, e.g. /blog
url: "https://muramiha.github.io" # the base hostname & protocol for your site, e.g. http://example.com
repository: A1Asriel/AsrielBot-site1

# Build settings
plugins:
  - jekyll-feed
  - jekyll-paginate-v2

pagination:
  enabled: true
  per_page: 10
  permalink: '/news/:num/'
  sort_reverse: true
  title: ':title'
  trail:
    before: 1
    after: 1

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      permalink: "/news/:title/"
  - scope:
      path: ""
    values:
      layout: "default"
